### ISSUE TITLE
Extension is not working on google.fr domain

### ISSUE THREAD

**Issue by clavat** [monsieurnebo/chrome-extension-google-results-clickable-map#5]
Hello,

First thanks for this idea, its very frustrating to loose this kind of key fonctinalities from Google...

But I'm french and I'm using google.fr, on this domain your extension is not working, it do nothing.

Can you help me here.
Thanks.

**Comment by monsieurnebo** [comment]
Hi @clavat !

Thanks for reporting this issue. It has been [fixed](https://github.com/monsieurnebo/chrome-extension-google-results-clickable-map/commit/41170e76d4ed2d0c519434be4f29febc1d96eee7) and will be shipped in the next release.

I'm closing this issue :)
